@echo off
cd /d "%~dp0"
echo Starting Namelist Manager...
if not exist "node_modules" (
    echo node_modules not found. Installing dependencies...
    call npm install
)
echo.
echo Opening Browser...
start http://localhost:5173
echo Starting Server...
npm run dev
pause
